# Generated by Django 3.1.5 on 2021-01-25 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Name',
            new_name='prodect',
        ),
    ]
