# Generated by Django 3.1.5 on 2021-01-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0002_auto_20210125_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodect',
            name='brice',
            field=models.IntegerField(verbose_name='عدد الامتار في الكرتونة'),
        ),
        migrations.AlterField(
            model_name='prodect',
            name='buybrice',
            field=models.IntegerField(verbose_name=' سعر بيع المنتج للعملاء العاديين'),
        ),
        migrations.AlterField(
            model_name='prodect',
            name='cwan',
            field=models.IntegerField(verbose_name='عدد الموجود من المنتج'),
        ),
        migrations.AlterField(
            model_name='prodect',
            name='jomlprice',
            field=models.IntegerField(verbose_name=' سعر بيع المنتج لعملاء الجملى'),
        ),
        migrations.AlterField(
            model_name='prodect',
            name='price',
            field=models.IntegerField(verbose_name='سعر شراء المنتج '),
        ),
    ]
