# Generated by Django 3.1.5 on 2021-01-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0003_auto_20210125_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodect',
            name='buybrice',
            field=models.IntegerField(verbose_name=' سعر بيع المتر للعملاء العاديين'),
        ),
        migrations.AlterField(
            model_name='prodect',
            name='cwan',
            field=models.IntegerField(help_text='اكتب عدد الكراتين الموجودة من هذا المنتج', verbose_name='عدد الموجود من المنتج'),
        ),
        migrations.AlterField(
            model_name='prodect',
            name='jomlprice',
            field=models.IntegerField(verbose_name=' سعر بيع المتر لعملاء الجملى'),
        ),
    ]
