# Generated by Django 3.1.5 on 2021-01-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0004_auto_20210125_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodect',
            name='cwan',
            field=models.IntegerField(help_text='اكتب عدد الكراتين الموجودة من هذا المنتج', verbose_name='عدد المشترى من المنتج'),
        ),
    ]
