# Generated by Django 3.1.5 on 2021-01-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0005_auto_20210125_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodect',
            name='jomlprice',
            field=models.IntegerField(verbose_name=' سعر بيع المتر لعملاء الجملة'),
        ),
    ]
