# Generated by Django 3.1.5 on 2021-01-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0008_auto_20210125_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodect',
            name='kind',
            field=models.CharField(choices=[('فرز اول', 'فرز اول'), ('فرز ثاني', 'فرز ثاني'), ('فرز ثالث', 'فرز ثالث')], max_length=50, null=True, verbose_name=''),
        ),
    ]
