# Generated by Django 3.1.5 on 2021-01-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0009_prodect_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodect',
            name='kind',
            field=models.CharField(choices=[('فرز اول', 'فرز اول'), ('فرز ثاني', 'فرز ثاني'), ('فرز ثالث', 'فرز ثالث')], max_length=50, null=True, verbose_name='النوع'),
        ),
    ]
