# Generated by Django 3.1.5 on 2021-01-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0011_prodect_com'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodect',
            name='com',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True, verbose_name='عدد الامتار الموجودة من المنتج'),
        ),
    ]
