# Generated by Django 3.1.5 on 2021-01-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0012_auto_20210126_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodect',
            name='com',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='عدد الامتار الموجودة من المنتج'),
        ),
    ]
