# Generated by Django 3.1.5 on 2021-01-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0013_auto_20210126_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='prodect',
            options={'verbose_name': 'منتج', 'verbose_name_plural': 'المنتجات'},
        ),
        migrations.AlterField(
            model_name='prodect',
            name='com',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='عدد الامتار الموجودة من المنتج'),
        ),
    ]
