# Generated by Django 3.1.5 on 2021-01-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0017_auto_20210127_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodect',
            name='com',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='عدد الامتار الموجودة من المنتج'),
        ),
    ]
