# Generated by Django 3.1.5 on 2021-01-27 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0018_auto_20210127_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders5',
            name='count_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='العدد المطلوب'),
        ),
        migrations.AddField(
            model_name='orders5',
            name='count_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='العدد المطلوب'),
        ),
        migrations.AddField(
            model_name='orders5',
            name='count_4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='العدد المطلوب'),
        ),
        migrations.AddField(
            model_name='orders5',
            name='count_5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='العدد المطلوب'),
        ),
        migrations.AddField(
            model_name='orders5',
            name='count_6',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='العدد المطلوب'),
        ),
        migrations.AddField(
            model_name='orders5',
            name='prodect_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items5', to='stockapp.prodect', verbose_name='المنتج'),
        ),
        migrations.AddField(
            model_name='orders5',
            name='prodects3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items3', to='stockapp.prodect', verbose_name='المنتج'),
        ),
        migrations.AddField(
            model_name='orders5',
            name='prodects_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items2', to='stockapp.prodect', verbose_name='المنتج'),
        ),
        migrations.AddField(
            model_name='orders5',
            name='prodects_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items4', to='stockapp.prodect', verbose_name='المنتج'),
        ),
        migrations.AddField(
            model_name='orders5',
            name='prodects_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items6', to='stockapp.prodect', verbose_name='المنتج'),
        ),
    ]
