# Generated by Django 3.1.5 on 2021-01-30 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0021_auto_20210128_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodect',
            name='new',
        ),
    ]
