# Generated by Django 3.1.5 on 2021-02-02 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0023_auto_20210131_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodect',
            name='price',
        ),
        migrations.AlterField(
            model_name='orders5',
            name='count_5',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='العدد المطلوب'),
        ),
        migrations.AlterField(
            model_name='orders5',
            name='count_6',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='العدد المطلوب'),
        ),
        migrations.AlterField(
            model_name='orders5',
            name='prodect_5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items5', to='stockapp.prodect', verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='orders5',
            name='prodects3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items3', to='stockapp.prodect', verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='orders5',
            name='prodects_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items2', to='stockapp.prodect', verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='orders5',
            name='prodects_4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items4', to='stockapp.prodect', verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='orders5',
            name='prodects_6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items6', to='stockapp.prodect', verbose_name='المنتج'),
        ),
        migrations.CreateModel(
            name='mooward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم المورد')),
                ('coun', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='عدد الامتار الذي قد اشتريتها')),
                ('number', models.DecimalField(decimal_places=2, max_digits=90, verbose_name='ثمن الشراء')),
                ('price2', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='سعر شراء المتر')),
                ('count', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='عدد الكراتين')),
                ('caten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockapp.prodect', verbose_name='المنتج الذي اشتريته')),
            ],
        ),
    ]
