# Generated by Django 3.1.5 on 2021-02-02 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0024_auto_20210202_1753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mooward',
            options={'verbose_name': 'المشتري', 'verbose_name_plural': 'المشتريات'},
        ),
    ]
