# Generated by Django 3.1.5 on 2021-02-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0025_auto_20210202_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='mooward',
            name='date2s',
            field=models.DateField(null=True, verbose_name='وقت العملية '),
        ),
        migrations.AddField(
            model_name='mooward',
            name='date_times',
            field=models.DateTimeField(null=True, verbose_name='وقت عملية الشراء'),
        ),
    ]
