# Generated by Django 3.1.5 on 2021-02-02 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0026_auto_20210202_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mooward',
            name='date2s',
        ),
    ]
