# Generated by Django 3.1.5 on 2021-02-02 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0027_remove_mooward_date2s'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mooward',
            options={'verbose_name': 'مشتري', 'verbose_name_plural': 'المشتريات'},
        ),
    ]
