# Generated by Django 3.1.5 on 2021-02-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0028_auto_20210202_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodect',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='اسم المنتج'),
        ),
    ]
