# Generated by Django 3.1.5 on 2021-02-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0029_auto_20210202_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodect',
            name='name',
            field=models.CharField(default='ا', max_length=50, verbose_name='اسم المنتج'),
        ),
    ]
