# Generated by Django 3.1.5 on 2021-02-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0031_auto_20210205_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodect',
            name='kind2',
            field=models.CharField(choices=[('سيراميك', 'سيراميك'), ('الادوات الصحية', 'الادوات الصحية')], default='1', max_length=50, verbose_name='النوع'),
            preserve_default=False,
        ),
    ]
