# Generated by Django 3.1.5 on 2021-02-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0034_auto_20210206_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders5',
            name='count_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, null=True, verbose_name='العدد المطلوب'),
        ),
        migrations.AlterField(
            model_name='orders5',
            name='count_3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, null=True, verbose_name='العدد المطلوب'),
        ),
        migrations.AlterField(
            model_name='orders5',
            name='count_4',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, null=True, verbose_name='العدد المطلوب'),
        ),
        migrations.AlterField(
            model_name='orders5',
            name='count_6',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='العدد المطلوب'),
        ),
    ]
