# Generated by Django 3.1.5 on 2021-02-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0035_auto_20210206_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders5',
            name='count',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='الامتار المطلوبة'),
        ),
        migrations.AlterField(
            model_name='orders5',
            name='count_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, null=True, verbose_name='الامتار المطلوبة'),
        ),
        migrations.AlterField(
            model_name='orders5',
            name='count_3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, null=True, verbose_name='الامتار المطلوبة'),
        ),
        migrations.AlterField(
            model_name='orders5',
            name='count_4',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, null=True, verbose_name='الامتار المطلوبة'),
        ),
        migrations.AlterField(
            model_name='orders5',
            name='count_5',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, null=True, verbose_name='الامتار المطلوبة'),
        ),
        migrations.AlterField(
            model_name='orders5',
            name='count_6',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='الامتار المطلوبة'),
        ),
    ]
