# Generated by Django 3.1.5 on 2021-02-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0036_auto_20210206_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodect',
            name='cwan',
            field=models.DecimalField(decimal_places=2, help_text='اكتب عدد الكراتين الموجودة من هذا المنتج', max_digits=100, verbose_name='عدد الكراتين الموجودة من المنتج'),
        ),
    ]
