# Generated by Django 3.1.5 on 2021-02-08 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0037_auto_20210206_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prodect',
            options={'verbose_name': 'صنف', 'verbose_name_plural': 'المخزن'},
        ),
    ]
