# Generated by Django 3.1.5 on 2021-02-09 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0038_auto_20210208_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders5',
            name='prodects_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items6', to='stockapp.prodect', verbose_name='المنتج'),
        ),
    ]
