# Generated by Django 3.1.5 on 2021-02-09 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0039_auto_20210209_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders5',
            name='prodect_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items5', to='stockapp.prodect', verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='orders5',
            name='prodects3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items3', to='stockapp.prodect', verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='orders5',
            name='prodects_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items2', to='stockapp.prodect', verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='orders5',
            name='prodects_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items4', to='stockapp.prodect', verbose_name='المنتج'),
        ),
    ]
