# Generated by Django 3.1.5 on 2021-02-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0040_auto_20210209_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders5',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='وقت عملية الشراء'),
        ),
    ]
