# Generated by Django 3.1.5 on 2021-02-10 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0042_auto_20210210_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders5',
            name='count2',
            field=models.DecimalField(decimal_places=2, default='1', max_digits=7, verbose_name='الامتار المطلوبة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders5',
            name='count_22',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, null=True, verbose_name='الامتار المطلوبة'),
        ),
        migrations.AddField(
            model_name='orders5',
            name='count_32',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, null=True, verbose_name='الامتار المطلوبة'),
        ),
        migrations.AddField(
            model_name='orders5',
            name='count_42',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, null=True, verbose_name='الامتار المطلوبة'),
        ),
        migrations.AddField(
            model_name='orders5',
            name='count_52',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, null=True, verbose_name='الامتار المطلوبة'),
        ),
        migrations.AddField(
            model_name='orders5',
            name='count_62',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='الامتار المطلوبة'),
        ),
        migrations.AddField(
            model_name='orders5',
            name='prodect_52',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items52', to='stockapp.prodect', verbose_name='المنتج'),
        ),
        migrations.AddField(
            model_name='orders5',
            name='prodects2',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='items22', to='stockapp.prodect', verbose_name='المنتج'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders5',
            name='prodects32',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items32', to='stockapp.prodect', verbose_name='المنتج'),
        ),
        migrations.AddField(
            model_name='orders5',
            name='prodects_22',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items222', to='stockapp.prodect', verbose_name='المنتج'),
        ),
        migrations.AddField(
            model_name='orders5',
            name='prodects_42',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items42', to='stockapp.prodect', verbose_name='المنتج'),
        ),
        migrations.AddField(
            model_name='orders5',
            name='prodects_62',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items62', to='stockapp.prodect', verbose_name='المنتج'),
        ),
    ]
