# Generated by Django 3.1.5 on 2021-01-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders5',
            options={'verbose_name': 'الطلب', 'verbose_name_plural': 'الطلبات'},
        ),
        migrations.RemoveField(
            model_name='orders5',
            name='num',
        ),
        migrations.AlterField(
            model_name='orders5',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='وقت عملية الشراء'),
        ),
        migrations.AlterField(
            model_name='orders5',
            name='date2',
            field=models.DateField(auto_now_add=True, help_text='الامتار', verbose_name='وقت عملية الشراء'),
        ),
    ]
