# Generated by Django 3.1.5 on 2021-01-27 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210126_1610'),
    ]

    operations = [
        migrations.DeleteModel(
            name='orders5',
        ),
    ]
